# MATH 210 Introduction to Mathematical Computing

## March 10, 2017

1. More linear algebra in SciPy
    * Matrix powers
    * Use diagonalization to compute matrix powers
    * Projections

In [1]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
%matplotlib inline

## 1. More linear algebra in SciPy

### Matrix powers

We've seen matrix multiplication of NumPy arrays using the `@` operator:

In [2]:
M = np.array([[2,1,],[-2,5]])
M

array([[ 2,  1],
       [-2,  5]])

In [3]:
M @ M

array([[  2,   7],
       [-14,  23]])

Remember that `M**2` is an array operation on NumPy arrays and computes the squares of each entry.

In [4]:
M**2

array([[ 4,  1],
       [ 4, 25]])

What if we want to compute higher powers of $M$ (as matrix multiplication) like $M^3 = M M M$? We need the function `numpy.linalg.matrix_power`.

In [5]:
np.linalg.matrix_power(M,2)

array([[  2,   7],
       [-14,  23]])

In [6]:
from numpy.linalg import matrix_power as mpow

In [7]:
mpow(M,2)

array([[  2,   7],
       [-14,  23]])

In [8]:
mpow(M,5)

array([[ -538,   781],
       [-1562,  1805]])

### Use diagonalization to compute matrix powers

If $M$ is an $n$ by $n$ matrix with $n$ real eigenvalues and $n$ distinct eigenvectors, then we can diagonalize $M$ as $M = PDP^{-1}$ where the columns of $P$ are the eigenvectors of $M$ and $D$ has corresponding eigenvalues along the diagonal.

Let's use this to construct a matrix with given eigenvalues $\lambda_1 = 3, \lambda_2 = 1$, and eigenvectors $v_1 = [1,1]^T, v_2 = [1,-1]^T$.

In [9]:
P = np.array([[1,1],[1,-1]])
P

array([[ 1,  1],
       [ 1, -1]])

In [10]:
D = np.diag((3,1))
D

array([[3, 0],
       [0, 1]])

In [11]:
M = P @ D @ la.inv(P)
M

array([[ 2.,  1.],
       [ 1.,  2.]])

In [12]:
evals, evecs = la.eig(M)

In [13]:
evals

array([ 3.+0.j,  1.+0.j])

In [14]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

Let's compute high powers of $M$ is two ways: (1) just by computing $M^k = MMMM\dots$ by matrix multiplication, (2) by $M = PDP^{-1}$ and $M^k = PD^kP^{-1}$

In [15]:
Pinv = la.inv(P)

In [16]:
k = 20

In [17]:
%timeit mpow(M,k)

The slowest run took 19.76 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 17.6 µs per loop


In [18]:
%timeit P @ D**k @ Pinv

The slowest run took 86.28 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.67 µs per loop


Using diagonalization computes powers of $M$ twice as a fast!

### Projections

The formula to project a vector $v$ onto a vector $w$ is

$$
\mathrm{proj}_w(v) = \frac{v \cdot w}{w \cdot w} w
$$

Let's a function called `proj` which computes the projection $v$ onto $w$.

In [19]:
def proj(v,w):
    '''Project vector v onto w.'''
    v = np.array(v)
    w = np.array(w)
    return np.sum(v * w)/np.sum(w * w) * w   # or (v @ w)/(w @ w) * w

In [20]:
proj([1,2,3],[1,1,1])

array([ 2.,  2.,  2.])