# MATH 210 Introduction to Mathematical Computing

## March 8, 2017

1. Linear algebra with SciPy
    * Matrix multiplication, transpose, inverse, determinant, trace 
2. Examples
    * Characteristic polynomials and Cayley-Hamilton Theorem
    * Eigenvalues, eigenvectors and symmetric matrices

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## 1. Linear algebra with SciPy

Matrix multiplication for NumPy arrays is performed by the operator `@`:

In [2]:
M = np.random.randint(0,10,[3,3])
M

array([[6, 8, 4],
       [1, 0, 4],
       [1, 6, 2]])

In [3]:
M @ M

array([[48, 72, 64],
       [10, 32, 12],
       [14, 20, 32]])

We can take the transpose with `.T` method:

In [4]:
M.T

array([[6, 1, 1],
       [8, 0, 6],
       [4, 4, 2]])

Notice that $M M^T$ is a symmetric matrix:

In [5]:
M @ M.T

array([[116,  22,  62],
       [ 22,  17,   9],
       [ 62,   9,  41]])

We can find the inverse using `scipy.linalg.inv`:

In [6]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [7]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

We find the determinant using `scipy.linalg.det`:

In [8]:
la.det(A)

-2.0

We can find the trace of a matrix using `numpy.trace`:

In [9]:
np.trace(A)

5

## 2. Examples

### Characteristic polynomials and Cayley-Hamilton Theorem

The characteristic polynomial of a 2 by 2 square matrix $A$ is

$$
p_A(\lambda) = \lambda^2 - \mathrm{tr}(A) \lambda + \mathrm{det}(A)
$$

The [Cayley-Hamilton Theorem](https://en.wikipedia.org/wiki/Cayley%E2%80%93Hamilton_theorem) says that every square matrix (of any size) satisfies its characteristic polynomial. For a matrix $A$ of size 2, this means that

$$
p_A(A) = A^2 - \mathrm{tr}(A) A + \mathrm{det}(A) I = 0
$$

Let's verify the Cayley-Hamilton Theorem for a few different matrices.

In [10]:
A

array([[1, 2],
       [3, 4]])

In [11]:
trace_A = np.trace(A)
det_A = la.det(A)
I = np.eye(2)

In [12]:
A @ A - trace_A * A + det_A * I

array([[ 0.,  0.],
       [ 0.,  0.]])

Let's do this again for some random matrices:

In [13]:
N = np.random.randint(0,10,[2,2])
N

array([[5, 9],
       [0, 1]])

In [14]:
trace_N = np.trace(N)
det_N = la.det(N)
I = np.eye(2)
N @ N - trace_N * N + det_N * I

array([[ 0.,  0.],
       [ 0.,  0.]])

### Eigenvalues, eigenvectors and symmetric matrices

The eigenvalues of a [symmetric matrix](https://en.wikipedia.org/wiki/Symmetric_matrix) are always real and the eigenvectors are always orthogonal! Let's verify these facts with some random matrices:

In [15]:
n = 4
P = np.random.randint(0,10,[n,n])
P

array([[2, 7, 8, 1],
       [9, 0, 3, 7],
       [5, 3, 1, 4],
       [5, 1, 0, 6]])

In [16]:
S = P @ P.T # This is a symmetric matrix
S

array([[118,  49,  43,  23],
       [ 49, 139,  76,  87],
       [ 43,  76,  51,  52],
       [ 23,  87,  52,  62]])

We can find the eigenvalues and eigenvectors using `scipy.linalg.eig`. Check the documentation:

In [17]:
la.eig?

We see that the output is a tuple where the first entry is an array containing the eigenvalues and the second entry is an array containing the corresponding eigenvectors in the columns. Let's unpack the eigenvalues and eigenvectors of $S$:

In [18]:
evals, evecs = la.eig(S)

In [19]:
evals

array([ 270.10895769+0.j,   91.27140682+0.j,    1.18474059+0.j,
          7.43489490+0.j])

Notice that the eigenvalues are returned as complex dataypes but all the imaginary parts are zero. These are real numbers!

In [20]:
evecs

array([[ 0.40535287,  0.89781227, -0.16634911, -0.04416049],
       [ 0.6846171 , -0.31908057,  0.11728649, -0.64477197],
       [ 0.42050766, -0.03309572,  0.68986212,  0.58836064],
       [ 0.43607543, -0.30170414, -0.69473888,  0.48595341]])

Let's check that the eigenvectors are orthogonal to each other:

In [21]:
v1 = evecs[:,0] # First column is the first eigenvector
v1

array([ 0.40535287,  0.6846171 ,  0.42050766,  0.43607543])

In [22]:
v2 = evecs[:,1] # Second column is the second eigenvector
v2

array([ 0.89781227, -0.31908057, -0.03309572, -0.30170414])

In [23]:
v1 @ v2

1.6653345369377348e-16

The dot product of eigenvectors $v_1$ and $v_2$ is zero (the number above is *very* close to zero and is due to rounding errors in the computations) and so they are orthogonal!