# MATH 210 Introduction to Mathematical Computing

## March 15, 2017

1. More about NumPy arrays
    * Dimension
    * Shape and reshape
    * hstack and vstack
    * Fancy indexing
2. More linear algebra examples
    * LU decomposition
    * Linear independence
3. Exercises

In [1]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
%matplotlib inline

## 1. More about NumPy arrays

NumPy arrays are the fundamental datatype for numerical computation in NumPy. Let's review and expand upon its [basic features](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#the-basics).

### Dimension

NumPy arrays can have any number of dimensions. A 1D NumPy array is like a list:

In [2]:
v = np.array([1,2,3])
v

array([1, 2, 3])

A 2D NumPy array is like matrix:

In [3]:
M = np.array([[1,2,3],[6,7,1]])
M

array([[1, 2, 3],
       [6, 7, 1]])

The `ndim` attribute returns the dimension of a NumPy array:

In [4]:
v.ndim

1

In [5]:
M.ndim

2

A 3D NumPy array is like a cube of numbers:

In [6]:
N = np.random.randint(0,10,(2,2,2))
N

array([[[4, 3],
        [1, 0]],

       [[0, 9],
        [9, 9]]])

In [7]:
N.ndim

3

### Shape and reshape

The `shape` attribute returns the [shape of a NumPy array](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#changing-the-shape-of-an-array) and we can change the shape of an array using the `reshape` method:

In [8]:
M.shape

(2, 3)

In [9]:
v.shape

(3,)

In [10]:
w = np.arange(0,16)
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
x = w.reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
x.shape

(4, 4)

In [13]:
x.ndim

2

In [14]:
w.shape

(16,)

In [15]:
w.ndim

1

### hstack and vstack

We can build bigger arrays out of smaller arrays by [stacking them vertically and horizontally](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#stacking-together-different-arrays). For example, we can vertically stack 3 different 1D arrays of length 3 into a 3 by 3 matrix.

In [16]:
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])

In [17]:
np.vstack((x,y,z))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [18]:
np.hstack((x,y,z))

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

Notice that the functions `vstack` and `hstack` take tuples of arrays.

Let's use `hstack` and `vstack` to build a block matrix $\begin{bmatrix} A & B \\ C & D \end{bmatrix}$.

In [19]:
A = np.ones(4).reshape(2,2)
B = 2*np.ones(4).reshape(2,2)
C = 3*np.ones(4).reshape(2,2)
D = 4*np.ones(4).reshape(2,2)

In [20]:
r1 = np.hstack((A,B))
r1

array([[ 1.,  1.,  2.,  2.],
       [ 1.,  1.,  2.,  2.]])

In [21]:
r2 = np.hstack((C,D))
r2

array([[ 3.,  3.,  4.,  4.],
       [ 3.,  3.,  4.,  4.]])

In [22]:
np.vstack((r1,r2))

array([[ 1.,  1.,  2.,  2.],
       [ 1.,  1.,  2.,  2.],
       [ 3.,  3.,  4.,  4.],
       [ 3.,  3.,  4.,  4.]])

### Fancy indexing

[Fancy indexing](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#fancy-indexing-and-index-tricks) allows us to access entries, rows, and columns of NumPy arrays in sophisticated ways.

But first, we recall basic indexing: we access the entry in the $i$th row and $j$th column using the bracket notation `A[i,j]`.

In [23]:
A = np.random.randint(-9,10,(4,4))
A

array([[ 7,  3, -9, -1],
       [ 3, -7, -2,  1],
       [-2, -4,  0, -4],
       [-8,  4,  8, -3]])

In [24]:
A[0,0]

7

In [25]:
A[2,3]

-4

We pass in a list of indices to access certain rows and columns:

In [26]:
A[[1,2],:]

array([[ 3, -7, -2,  1],
       [-2, -4,  0, -4]])

The colon means "all" therefore the code above selects entries from all the columns which are in rows 1 or 2. For example, to select the first column of `A`, we use the code:

In [27]:
col = A[:,0]

In [28]:
col

array([ 7,  3, -2, -8])

We can use a [boolean array](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#indexing-with-boolean-arrays) to access entries in an array:

In [29]:
A

array([[ 7,  3, -9, -1],
       [ 3, -7, -2,  1],
       [-2, -4,  0, -4],
       [-8,  4,  8, -3]])

In [30]:
A > 0

array([[ True,  True, False, False],
       [ True, False, False,  True],
       [False, False, False, False],
       [False,  True,  True, False]], dtype=bool)

In [31]:
A[A > 0]

array([7, 3, 3, 1, 4, 8])

In [32]:
A[np.array([0,1,2,3]) != 2,:] # Select the all rows except the row at index 2

array([[ 7,  3, -9, -1],
       [ 3, -7, -2,  1],
       [-8,  4,  8, -3]])

## 2. More examples from linear algebra

The LU factorization of a matrix $A$ is decomposes $A$ into 3 matrices

$$
A = PLU
$$

where $P$ is a permutation matrix, $L$ is lower triangular and $U$ is upper triangular. The matrix $U$ is (more or less) the row echelon form of $A$.

For example, consider the matrix

$$
A = \begin{bmatrix}
3 & 2 \\ -1 & -1
\end{bmatrix}
$$

Adding $1/3$ times the first to the second row gives a row echelon form of $A$:

$$
\begin{bmatrix}
3 & 2 \\ 0 & -1/3
\end{bmatrix}
$$

In [33]:
A = np.array([[3,2],[-1,-1]])
A

array([[ 3,  2],
       [-1, -1]])

The $LU$ factorization of $A$ is:

In [34]:
P, L, U = la.lu(A)

In [35]:
P

array([[ 1.,  0.],
       [ 0.,  1.]])

In [36]:
L

array([[ 1.        ,  0.        ],
       [-0.33333333,  1.        ]])

In [37]:
U

array([[ 3.        ,  2.        ],
       [ 0.        , -0.33333333]])

This is the same matrix as the row echelon form we found above! And if we compute the matrix multiplication $PLU$ we can reconstruct $A$:

In [38]:
P @ L @ U

array([[ 3.,  2.],
       [-1., -1.]])

### Finding a basis of the linear span of vectors

We can use the $LU$ factorization to find a basis for the span of vectors $v_1, \dots, v_n$ by stacking the vectors into the rows a matrix $A$ and then computing $U$ in the $LU$ factorization. For example, let's find a basis for the span of the vectors:

$$
u_1 = \begin{bmatrix} 17 \\ 1 \\ -4 \\ 7 \end{bmatrix} \ \ 
u_2 = \begin{bmatrix} 15 \\ -24 \\ -28 \\ 3 \end{bmatrix} \ \
u_3 = \begin{bmatrix} 7 \\ 10 \\ -6 \\ 2 \end{bmatrix} \ \
u_4 = \begin{bmatrix} -26 \\ 23 \\ 34 \\ -7 \end{bmatrix}
$$

In [39]:
u1 = np.array([17,1,-4,7])
u2 = np.array([15,-24,-28,3])
u3 = np.array([7,10,-6,2])
u4 = np.array([-26,23,34,-7])

In [40]:
A = np.vstack((u1,u2,u3,u4))
A

array([[ 17,   1,  -4,   7],
       [ 15, -24, -28,   3],
       [  7,  10,  -6,   2],
       [-26,  23,  34,  -7]])

In [41]:
P,L,U = la.lu(A)

In [42]:
print(U)

[[ -2.60000000e+01   2.30000000e+01   3.40000000e+01  -7.00000000e+00]
 [  0.00000000e+00   1.61923077e+01   3.15384615e+00   1.15384615e-01]
 [  0.00000000e+00   0.00000000e+00   1.51068884e+01   2.30878860e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -1.77635684e-15]]


Notice that bottom right entry very close to 0. In fact, the true value is zero and we see that the linear span of the four vectors $u_1$, $u_2$, $u_3$ and $u_4$ has dimension 3 and rows of $U$ give us a basis of the span.

## 3. Exercises

**Exercise.** Use the functions `diag`, `hstack` and `vstack` to create the 2D NumPy array

$$
\begin{bmatrix}
1 & 0 & 0 & 7 & 0 & 0 \\
0 & -1 & 0 & 0 & 2 & 0 \\
0 & 0 & 2 & 0 & 0 & -1 \\
5 & 0 & 0 & 6 & 0 & 0 \\
0 & 3 & 0 & 0 & -3 & 0 \\
0 & 0 & 1 & 0 & 0 & 8
\end{bmatrix}
$$

**Exercise.** Create a 5 by 5 matrix with random integer entries sampled from the interval $[0,9]$ and use fancy indexing to create the 2 by 2 matrix consisting of the corner entries (ie. entries at (0,0), (0,4), (4,0) and (4,4)).

**Exercise.** Write a function which takes an input parameter $A$, $i$ and $j$ and returns the dot product of the $i$th and $j$th row (indexing starts at 0).